### ISSUE TITLE
update (or replace?) the included node-irc library

### ISSUE THREAD

**Issue by galgeek** [mozilla/testdaybot#39]
The code here looks like v.0.3.3.

0.3.5 was released by the original maintainer 2013-01-01. https://github.com/martynsmith/node-irc/releases

Current node-irc 0.3.x branch shows 0.3.7 in package.json

A possible replacement, mentioned in node-irc issues conversations:  https://github.com/oftn/oftn-bot

**Comment by whimboo** [comment]
PR #45 has been merged. Thanks.

**Comment by whimboo** [comment]
Marking priority as P1 given that this fixes the crash for non-online users and whois().
