### ISSUE TITLE
save and reload test day data across bot restarts

### ISSUE THREAD

**Issue by galgeek** [mozilla/testdaybot#43]
The bot does not currently save its test day schedule to reload after a bot restart. Instead, a previously schedule test day must be rescheduled.

We should save a test day schedule, and probably some other details like updated helpers, and reload when the bot restarts.

**Comment by whimboo** [comment]
Commits have been squashed, the commit message updated, and the PR got merged as https://github.com/mozilla/testdaybot/commit/5ef21bad513fd5c9322d9d410a4ab4383433fc8a.
