### ISSUE TITLE
Log active participants

### ISSUE THREAD

**Issue by whimboo** [mozilla/testdaybot#44]
Before we were putting out greeted people in the stats. Given that we do not greet people anymore, we should change that to active people. That means we should log who was active during a testday. 

@ashughes1 I think that is something you absolutely wants to have for the first testday?

**Comment by galgeek** [comment]
Hi @ashughes1 and @whimboo!

The data-recording code hasn't changed, we're just not sending the greeting.
As long as we're not sending a greeting, it might be good to change the property names from greetedName and greetedNumber, maybe to usersJoined and usersJoinedTotal.

**Comment by whimboo** [comment]
We do not want to count the users who joined the channel but those who were active. So `activeName` and `activeNumber` would be good. Whereby if activeName is an array we don't need the number property because there is the length available.

**Comment by galgeek** [comment]
usersTalked already records active participants.

Should we rename or remove any of the current properties?

**Comment by whimboo** [comment]
I see. Then I leave it up to @ashughes1. If he doesn't need the join information, we can get it removed.

**Comment by ashughes1** [comment]
I don't think "joined" is too valuable because it will count lurkers and auto-joiners. Particularly now since the events are done in the #qa channel. I'm only interested in counting the people who are joining the channel for the given event. I don't know a good way to differentiate between lurkers/auto-joiners, joining #qa for general interest, and joining #qa for the event.

**Comment by galgeek** [comment]
Hi @ashughes1!

The current "greeted" properties record nicks that join during a testday; they don't include those already in the channel when a test day begins. Maybe it would be interesting to compare "greeted" to active ("usersTalked")?

testdaybot updates are running in #testdaybotTest. You might want to ` /msg _TestDayBot :stats` to see what we're currently collecting.

**Comment by whimboo** [comment]
PR #46 has been merged and adds logging for active users.
