### ISSUE TITLE
Announce in the channel when the test gets started or ends

### ISSUE THREAD

**Issue by whimboo** [mozilla/testdaybot#50]
Right now the bot is only updating the topic of the channel. But it would be good to send a simple message to the channel itself to announce that the testday has been started or ends. It should show the topic and the link to the etherpad like:

`The %topic% testday starts now. For details see %etherpad%`
[..]
`The %topic% testday ended. Thank you all for your participation!`

@ashughes1, would this wording be fine with you.

**Comment by ashughes1** [comment]
That looks fine to me, thanks.

**Comment by whimboo** [comment]
@galgeek can you please get this fixed for tomorrow?

**Comment by whimboo** [comment]
PR #61 has been merged
