### ISSUE TITLE
refine commands and add :rmAdmin and :rmHelper

### ISSUE THREAD

**Issue by galgeek** [mozilla/testdaybot#54]
Hello @whimboo and @ashughes1!

Anthony provided some quick feedback on his testing today, including...
* refine the :etherpad command, so that it's smarter about what it says, like :schedule
* refine the :addAdmin/:addHelper commands, so that they don't add duplicate nicks
* refine the :optout command, so that it adds advice on opting back in 
* refine the :advertise command, so that it provides feedback on what it does
* add :rmAdmin and :rmHelper commands

**Comment by whimboo** [comment]
PR #55 has been merged.
