### ISSUE TITLE
Setting testday topic needs a prefix welcome message

### ISSUE THREAD

**Issue by whimboo** [mozilla/testdaybot#57]
Right now we have the following line:

> client.send('TOPIC', testDay.channel, testDay.topic);

It should be changed so it fulfills the following:

* A welcome text
* It includes the link to the etherpad + some prefix text

@ashughes1 can you please give us the wording you would like to have here? @galgeek, this is an issue we also have to fix before Friday.

**Comment by ashughes1** [comment]
I guess something like this will do:

> Welcome to the QA channel. Today we're testing <topic>. Please read <etherpad> for more information and ask any questions you have in this channel.

**Comment by whimboo** [comment]
> Welcome to the QA channel. Today we're testing . Please read for more information and ask any questions you have in this channel.

I assume you missed to add the topic and etherpad link here. So what about:

`Welcome to the QA channel. Today we have a %topic%. For more information see %etherpad% and ask any questions you have in this channel`

**Comment by ashughes1** [comment]
> I assume you missed to add the topic and etherpad link here. So what about:
>
> Welcome to the QA channel. Today we have a %topic%. For more information see %etherpad% and ask any questions you have in this channel

Sorry, github ate the tags I added. This is what I meant:

> Welcome to the QA channel. Today we are testing %topic%. Please read %etherpad% for more information and ask any questions you have in this channel.

**Comment by whimboo** [comment]
PR #60 has been merged.
