### ISSUE TITLE
:helper add should support addition of multiple helpers per command

### ISSUE THREAD

**Issue by galgeek** [mozilla/testdaybot#71]
Currently only one nick can be added per command.

**Comment by xabolcs** [comment]
Hi all!
I'd like to take this issue!

@galgeek, do you have thoughts how to response to bad inputs, like not all nicknames are registered?

**Comment by galgeek** [comment]
Hi, @xabolcs!

I think it's enough for this issue to do whatever checks testdaybot does now.

Before testdaybot runs any admin command, it checks that the nick is on the admins list and that the nick is registered and logged in, so it's not vital to do further checks simply to add a nick to the list. 

Also, if I remember correctly, it's not clear how to do any check for a nick that's not currently signed in, and it's good to be able to support adding a nick that isn't currently signed in, too.

**Comment by xabolcs** [comment]
Thanks!

Should I improve `:admin` add/remove commands too? Then please update the issue's title to reflect that!

**Comment by whimboo** [comment]
I do not see a need for such a functionality. Each command should only operate on a single nick similar to nickserv, chanserv, or other kinds of software.

**Comment by xabolcs** [comment]
@whimboo feel free to close this as wontfix, also the PR!

**Comment by whimboo** [comment]
Thanks @xabolcs for the feedback. I'm still sure we should not implement this. So I will finally close both tickets.
