### ISSUE TITLE
Improve time handling in :next command

### ISSUE THREAD

**Issue by whimboo** [mozilla/testdaybot#74]
From issue #52:

2. When setting the ":next" testday make "time" errors more explicit:
a) start time in the past
b) start time after end time
Currently we get the same generic error that time is invalid and have to hunt down where the issue is.

@FlorinMezei it would be good if you can give some examples here. Thanks.

**Comment by FlorinMezei** [comment]
Some simple examples:

a) start time in the past
A simple check if start time is before current time - show an error saying something like: "Start time is set in the past - note that the timezone is UTC"

a) start time after end time
A simple check if start time is before end time - show an error saying something like: "Start time was set after End Time"

**Comment by xabolcs** [comment]
Can I take this?

**Comment by whimboo** [comment]
Sure! ;) I assigned you now.

**Comment by whimboo** [comment]
PR #77 has been merged. I will get all the latest changes merged to the release branch now, so they will be active on the running testdaybot instance in #qa in a bit.
