### ISSUE TITLE
Original State failed to show "Search" in the search field.

### ISSUE THREAD

**Issue by FahimaZulfath** [mozilla/testdaybot#85]
Step to Reproduce:
1) Download [Firefox 56 Beta 4:](https://archive.mozilla.org/pub/firefox/candidates/56.0b4-candidates/build2/)
2) Make a clear profile
3) Go to about:config and search for "browser.preferences.search" and set it value to true.
4) Go to "about:preferences"

Actual Result:
        Text is displayed as "Find in Options" instead of "Search" in the search field.

Expected Result:
             "Search" text is displayed on the right side of the search field and the "search" icon is displayed on the left.

OS: Windows 10.0 X 64 - bit
Build ID: 20170818035007
 [testday-20170818]

![bug1](https://user-images.githubusercontent.com/22166013/29469541-5f01961c-8466-11e7-8a7f-3e8286e22817.png)

**Comment by whimboo** [comment]
@FahimaZulfath if you wanted to file a bug against Firefox then please use Bugzilla. This repository is used for something completely different.

**Comment by FahimaZulfath** [comment]
These issues were reported under the test day Fx 56 beta 4. Had last friday
18-08-2017. We have to report the build here only. Reopen it still it is
not fixed.

**Comment by whimboo** [comment]
Again, this is not the right place to report bugs about Firefox. This is the repository for a bot tool for IRC which helps on test days. Again, report those bugs in Bugzilla.
