### ISSUE TITLE
about:preferences#searchResults contains link with text label "Firefox Support"

### ISSUE THREAD

**Issue by FahimaZulfath** [mozilla/testdaybot#86]
Step to Reproduce:

1. Download [Firefox 56 Beta 4](https://archive.mozilla.org/pub/firefox/candidates/56.0b4-candidates/build2/)
2. Make a clean profile
3. Go to about:config and search for "browser.preferences.search" and set it value to true.
4. Go to "about:preferences"
5. Start typing to search for something that doesn't have search results in preferences (e.g asd).
6. **Sorry! There are no results in Options for "asd"** message is displayed
"Options" in Windows
"Preferences" in Mac OS and Linux

Actual Result:
     about:preferences#searchResults has **Need help? Visit Firefox Support** instead of Nightly Support 
  
Expected Result:
   The very next line has **Need help? Visit Nightly Support ** is displayed.

![bug1](https://user-images.githubusercontent.com/22166013/29472070-1f239fe0-8470-11e7-907b-0351b6d20b1b.png)

OS: Windows 10.0 X 64 - bit
Build ID: 20170818035007
[testday-20170818]

**Comment by whimboo** [comment]
@FahimaZulfath if you wanted to file a bug against Firefox then please use Bugzilla. This repository is used for something completely different.
