### ISSUE TITLE
Enable Container Tab is not found in about:preferences

### ISSUE THREAD

**Issue by FahimaZulfath** [mozilla/testdaybot#87]
Step to Reproduce:

1. Launch Firefox
2. Go to "about:preferences".

Actual Result:
   "Enable container tab" is not found in general, search, privacy & security, firefox account.

Expected Result:
   "Enable Container Tabs" checkbox should present under Tabs in General. It is moved to General from Privacy & Security tab.
OS: Windows 10.0 X 64 - bit
Build ID: 20170818035007
[testday-20170818]

**Comment by whimboo** [comment]
@FahimaZulfath if you wanted to file a bug against Firefox then please use Bugzilla. This repository is used for something completely different.
