### ISSUE TITLE
Under Application (about:peferences#general) string does'nt changed

### ISSUE THREAD

**Issue by FahimaZulfath** [mozilla/testdaybot#88]
Step to Reproduce:

1. Launch Firefox
2. Go to "about:preferences".
3. In the General tab check the "Files and Applications" section - Applications

Expected Result:
"""Files and Applications"" section moved to General tab from ""Privacy & Security"" tab - Content remaining the same, except:
String changed - ""Choose how Nightly handles the files you download from the Web or the applications you use while browsing."" changed to ""Choose how Nightly handles the files you download from the web or the applications you use while browsing.

Actual Result:
 String does not changed. "Choose how Nightly handles the files you download from the Web or the applications you use while browsing." appears under applications.
![image](https://user-images.githubusercontent.com/22166013/29496314-8ce608fa-85ed-11e7-9833-76a7e7e05415.png)

**Comment by whimboo** [comment]
@FahimaZulfath if you wanted to file a bug against Firefox then please use Bugzilla. This repository is used for something completely different.
