### ISSUE TITLE
Ellipsis are not added to "Manage Account" in about:preferences#sync

### ISSUE THREAD

**Issue by FahimaZulfath** [mozilla/testdaybot#89]
Step to Reproduce:

1. Launch Firefox
2. Go to "about:preferences"
3. In the Firefox Account tab - check the "Firefox Account" section

Expected result:
  Strings changed and ellipsis added to Manage account

Actual Result:
  Ellipsis is not added to Manage Account

![image](https://user-images.githubusercontent.com/22166013/29496447-62139e8c-85f0-11e7-93ac-e1cd09c9d50e.png)

**Comment by whimboo** [comment]
@FahimaZulfath if you wanted to file a bug against Firefox then please use Bugzilla. This repository is used for something completely different.
